- name: Build And Deploy
  uses: Azure/static-web-apps-deploy@v1
  with:
    azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
    action: upload
    app_location: "/"               # Root of your static files
    output_location: "."            # No build folder
    skip_app_build: true            # ✅ Prevents Oryx from trying to build
